### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/giga_connectome#43]
I have set up a gist for actual documentations, but still there are lots of things to be filled.
See the latest version (built from main branch) [here](https://giga-connectome.readthedocs.io/en/latest/)

It will be great to have your help on this one @clarkenj. Feel free to pick one or more sections to write!

- [x] Installation: need details of installing MIST etc -> will be resolve by #97
- [x] Workflow #3 
- [x] Outputs and explain the structure -> #80
- [x] Usage note: more details on config files  -> #108 
- [x] `utils` docstrings -> solved by Remi long ago
